sudo: required

services:
  - docker

before_install:
  - docker build -t ronaldreeggan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ronaldreeggan/react-test npm run test -- --coverage

after_success:
  #build images
  - docker build -t ronaldreeggan/multi-docker-client ./client
  - docker build -t ronaldreeggan/multi-docker-nginx ./nginx
  - docker build -t ronaldreeggan/multi-docker-server ./server
  - docker build -t ronaldreeggan/multi-docker-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push to docker hub
  - docker push ronaldreeggan/multi-docker-client
  - docker push ronaldreeggan/multi-docker-nginx
  - docker push ronaldreeggan/multi-docker-server
  - docker push ronaldreeggan/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-227351385473"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

    